"""orders domain and settings

Revision ID: 0275fa5bfee4
Revises: 7fceea006abe
Create Date: 2026-07-20 10:20:10.505014

"""
import csv
from pathlib import Path
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0275fa5bfee4'
down_revision: Union[str, Sequence[str], None] = '7fceea006abe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('remote_area_zips',
    sa.Column('zip_code', sa.String(length=5), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('region_name', sa.String(length=100), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('jeju', 'island')", name='ck_remote_area_zips_kind'),
    sa.PrimaryKeyConstraint('zip_code')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('recipient_name', sa.String(length=50), nullable=False),
    sa.Column('recipient_phone', sa.String(length=20), nullable=False),
    sa.Column('postal_code', sa.String(length=5), nullable=False),
    sa.Column('address1', sa.String(length=255), nullable=False),
    sa.Column('address2', sa.String(length=255), nullable=False),
    sa.Column('order_note', sa.String(length=500), nullable=False),
    sa.Column('deposit_due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("payment_status IN ('pending_payment', 'paid', 'canceled')", name='ck_orders_payment_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('sub_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('shipping_status', sa.String(length=20), nullable=True),
    sa.Column('shipping_fee', sa.Integer(), nullable=False),
    sa.Column('remote_extra_fee', sa.Integer(), nullable=False),
    sa.Column('carrier', sa.String(length=50), nullable=True),
    sa.Column('tracking_number', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("shipping_status IS NULL OR shipping_status IN ('preparing', 'shipping', 'delivered')", name='ck_sub_orders_shipping_status'),
    sa.CheckConstraint('remote_extra_fee >= 0', name='ck_sub_orders_remote_extra_fee'),
    sa.CheckConstraint('shipping_fee >= 0', name='ck_sub_orders_shipping_fee'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'seller_id')
    )
    # ix_sub_orders_order_id는 생성하지 않음 — UNIQUE(order_id, seller_id)가 선행 컬럼 인덱스 역할
    op.create_index(op.f('ix_sub_orders_seller_id'), 'sub_orders', ['seller_id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sub_order_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('product_name', sa.String(length=100), nullable=False),
    sa.Column('option_text', sa.String(length=120), nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('extra_price', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ordered', 'canceled')", name='ck_order_items_status'),
    sa.CheckConstraint('quantity >= 1 AND quantity <= 999', name='ck_order_items_quantity'),
    sa.CheckConstraint('unit_price >= 0', name='ck_order_items_unit_price'),
    sa.ForeignKeyConstraint(['sub_order_id'], ['sub_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_sub_order_id'), 'order_items', ['sub_order_id'], unique=False)
    # ### end Alembic commands ###

    # 시드 ① 도서산간 우편번호 — 번들 CSV (출처·보정 내역은 CSV 헤더 주석)
    csv_path = Path(__file__).resolve().parents[2] / "app" / "orders" / "data" / "remote_area_zips.csv"
    with csv_path.open(encoding="utf-8-sig") as f:  # BOM 유입 방어 — 재저장된 파일도 안전
        rows = [r for r in csv.DictReader(line for line in f if not line.startswith("#"))]
    # 오염된 CSV로 조용히 성공하지 않도록 검증 후 실패 fast (앞자리 0 탈락·중복·헤더 붕괴 방어)
    import re
    assert rows and all(r.keys() == {"zip_code", "kind", "region_name"} for r in rows), "CSV 헤더 불일치"
    assert all(re.fullmatch(r"\d{5}", r["zip_code"]) for r in rows), "5자리 아닌 zip_code 존재"
    assert all(r["kind"] in ("jeju", "island") for r in rows), "kind 값 오류"
    assert len(rows) == len({r["zip_code"] for r in rows}), "중복 zip_code 존재"
    op.bulk_insert(
        sa.table("remote_area_zips", sa.column("zip_code", sa.String), sa.column("kind", sa.String), sa.column("region_name", sa.String)),
        rows,
    )

    # 시드 ② settings — 값 변경은 DB로 (AD-13). deposit_account 실계좌는 Slur 제공 후 갱신
    op.bulk_insert(
        sa.table("settings", sa.column("key", sa.String), sa.column("value", sa.Text), sa.column("description", sa.String)),
        [
            {"key": "deposit_account", "value": "은행/계좌번호/예금주 미설정", "description": "무통장입금 안내 계좌 (실계좌로 갱신 필요)"},
            {"key": "unpaid_cancel_days", "value": "3", "description": "미입금 자동취소 기한 (일)"},
            {"key": "low_stock_threshold", "value": "5", "description": "품절 임박 기준 재고 수량"},
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_items_sub_order_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_sub_orders_seller_id'), table_name='sub_orders')
    op.drop_table('sub_orders')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_table('settings')
    op.drop_table('remote_area_zips')
    # ### end Alembic commands ###
