"""sellers

Revision ID: 16a1879f8881
Revises: ca64b8ab1e3b
Create Date: 2026-07-16 17:28:29.710581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16a1879f8881'
down_revision: Union[str, Sequence[str], None] = 'ca64b8ab1e3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sellers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('brand_name', sa.String(length=50), nullable=False),
    sa.Column('brand_intro', sa.String(length=500), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('representative_name', sa.String(length=50), nullable=False),
    sa.Column('business_registration_number', sa.String(length=10), nullable=False),
    sa.Column('mail_order_number', sa.String(length=50), nullable=False),
    sa.Column('business_address', sa.String(length=255), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=False),
    sa.Column('base_shipping_fee', sa.Integer(), server_default='0', nullable=False),
    sa.Column('jeju_extra_fee', sa.Integer(), server_default='0', nullable=False),
    sa.Column('island_extra_fee', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['seller_applications.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sellers')
    # ### end Alembic commands ###
