"""variants

Revision ID: 755424d010a0
Revises: 802baf4b79a7
Create Date: 2026-07-16 23:40:37.859293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '755424d010a0'
down_revision: Union[str, Sequence[str], None] = '802baf4b79a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('variants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('option1_name', sa.String(length=20), nullable=False),
    sa.Column('option1_value', sa.String(length=30), nullable=False),
    sa.Column('option2_name', sa.String(length=20), nullable=False),
    sa.Column('option2_value', sa.String(length=30), nullable=False),
    sa.Column('extra_price', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('stock >= 0', name='ck_variants_stock'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'option1_value', 'option2_value')
    )
    op.create_index(op.f('ix_variants_product_id'), 'variants', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_variants_product_id'), table_name='variants')
    op.drop_table('variants')
    # ### end Alembic commands ###
