"""seller_applications

Revision ID: ca64b8ab1e3b
Revises: 7b39984edd2b
Create Date: 2026-07-16 17:17:55.422007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca64b8ab1e3b'
down_revision: Union[str, Sequence[str], None] = '7b39984edd2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seller_applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('representative_name', sa.String(length=50), nullable=False),
    sa.Column('business_registration_number', sa.String(length=10), nullable=False),
    sa.Column('mail_order_number', sa.String(length=50), nullable=False),
    sa.Column('business_address', sa.String(length=255), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=False),
    sa.Column('brand_name', sa.String(length=50), nullable=False),
    sa.Column('brand_intro', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected')", name='ck_seller_applications_status'),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seller_applications_user_id'), 'seller_applications', ['user_id'], unique=False)
    op.create_index('uq_seller_applications_pending', 'seller_applications', ['user_id'], unique=True, postgresql_where=sa.text("status = 'pending'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_seller_applications_pending', table_name='seller_applications', postgresql_where=sa.text("status = 'pending'"))
    op.drop_index(op.f('ix_seller_applications_user_id'), table_name='seller_applications')
    op.drop_table('seller_applications')
    # ### end Alembic commands ###
